#pragma once

#define MTOA_VAL(str) #str
#define MTOA_TOSTRING(str) MTOA_VAL(str)

#define MTOA_VENDOR "Solid Angle SL"
#define MTOA_ARCH_VERSION_NUM 1
#define MTOA_MAJOR_VERSION_NUM 2
#define MTOA_MINOR_VERSION_NUM 5
#define MTOA_FIX_VERSION "0"


#define MTOA_ARCH_VERSION         MTOA_TOSTRING(MTOA_ARCH_VERSION_NUM)
#define MTOA_MAJOR_VERSION         MTOA_TOSTRING(MTOA_MAJOR_VERSION_NUM)
#define MTOA_MINOR_VERSION         MTOA_TOSTRING(MTOA_MINOR_VERSION_NUM)

#define MTOA_VERSION MTOA_ARCH_VERSION "." MTOA_MAJOR_VERSION "." MTOA_MINOR_VERSION "." MTOA_FIX_VERSION

#ifndef MAYA_VERSION
   #define MAYA_VERSION "Any"
#endif
