#*********************************************************************
# content   = RV config
# date      = 2020-06-19
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>
#*********************************************************************


version:
path: "C:/Program Files/Tweak/RV/bin/rv.exe"

start:
