# content   = user config
# date      = 2020-06-19
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>

name:     Alexander Richter
id:       alexa
position: Technical Director

rights:   'admin'


# REPOSITORY **********************************************************
REPOSITORY:
  username: guest
  password:

  owner: alexanderrichtertd
  repository: plex
