

import os
 # MAYA


 # --- Path ---

"SCRIPT_PATH" : "SOFTWARE_PATH/scripts"
"PLUGINS_PATH" : "SOFTWARE_PATH/plugins"
"ARNOLD_PATH" : "PLUGINS_PATH/arnold"
"ARNOLD_SHADER_PATH" : "ARNOLD_PATH/alShader"

"MAYA_VERSION" : "2015"


 # --- SCRIPT ---
"MAYA_SCRIPT_PATH" : "SCRIPT_PATH/ANIM;MAYA_SCRIPT_PATH"
"MAYA_SCRIPT_PATH" : "PLUGINS_PATH/arctracker;MAYA_SCRIPT_PATH"
"MAYA_SCRIPT_PATH" : "PLUGINS_PATH/tweenmachine;MAYA_SCRIPT_PATH"


 # --- Python ---
"PYTHONPATH" : "STATUS_PATH;PYTHONPATH"
"PYTHONPATH" : "SOFTWARE_PATH;PYTHONPATH"
"PYTHONPATH" : "PIPELINE_PATH;PYTHONPATH"
"PYTHONPATH" : "LIBRARY_PATH;PYTHONPATH"
"PYTHONPATH" : "PLUGINS_PATH/ngskintools/scripts;PYTHONPATH"


 # --- Plugin ---
"MAYA_PLUG_IN_PATH" : "PLUGINS_PATH;MAYA_PLUG_IN_PATH;"
"MAYA_PLUG_IN_PATH" : "PLUGINS_PATH/ngskintools/plug-ins;MAYA_PLUG_IN_PATH;"
 # "MAYA_PLUG_IN_PATH" : "PLUGINS_PATH/SOuP/plug-ins/win_maya2015;MAYA_PLUG_IN_PATH"


 # --- Shelf ---
 # --- "MAYA_SHELF_PATH" : "PLUGINS_PATH/SOuP/shelves;MAYA_SHELF_PATH"
"MAYA_SHELF_PATH" : "SOFTWARE_PATH/shelf;MAYA_SHELF_PATH"


 # --- Icon ---
"XBMLANGPATH" : "PLUGINS_PATH/SOuP/icons;BXBMLANGPATH"


 # --- Arnold ---
"MtoA" : "ARNOLD_PATH/MAYA_VERSION"
"MAYA_MODULE_PATH" : "MtoA;MAYA_MODULE_PATH"
"PATH" : "MtoA/bin;PATH"
"ARNOLD_PLUGIN_PATH" : "MtoA/shaders;ARNOLD_PLUGIN_PATH;ARNOLD_PLUGIN_PATH"
"ARNOLD_PLUGIN_PATH" : "ARNOLD_PATH/bin;ARNOLD_PLUGIN_PATH;ARNOLD_PLUGIN_PATH"
"ARNOLD_PLUGIN_PATH" : "ARNOLD_SHADER_PATH/bin;ARNOLD_PLUGIN_PATH"
"MTOA_TEMPLATES_PATH" : "ARNOLD_SHADER_PATH/ae;MTOA_TEMPLATES_PATH"

"ARNOLD_LICENSE_HOST" : "blue"


 # --- RenderMan ---
"RM" : "PLUGINS_PATH/renderman/RenderManStudio-20.9-maya2015"
"MAYA_MODULE_PATH" : "RM/etc;MAYA_MODULE_PATH"
"RMSTREE" : "RM"
"PATH" : "RM/bin;PATH"


 # --- Disable Report ---
"MAYA_DISABLE_CIP" : "1"
"MAYA_DISABLE_CER" : "1"


 # --- MayaEnvVars ---
 # "MAYA_PROJECT" : "PROJECT_ROOT/2_production"
 # cd MAYA_PROJECT


 # --- SplashScreen ---
 # File: MayaEDUStartupImage.png
"XBMLANGPATH" : "IMG_PATH;XBMLANGPATH"


 # --- Call Maya ---
"MAYA_DIR" : "C:/Program Files/Autodesk/MayaMAYA_VERSION"
"PATH" : "MAYA_DIR/bin;PATH"
