# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../software/utilities/ui/arHeader_menu.ui'
#
# Created: Wed Jan 25 17:22:27 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(96, 199)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        Form.setFont(font)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wgMenu = QtGui.QWidget(Form)
        self.wgMenu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wgMenu.setObjectName("wgMenu")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.wgMenu)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.layMenu01 = QtGui.QVBoxLayout()
        self.layMenu01.setSpacing(8)
        self.layMenu01.setContentsMargins(0, -1, 0, -1)
        self.layMenu01.setObjectName("layMenu01")
        self.btnMenu01_item01 = QtGui.QPushButton(self.wgMenu)
        self.btnMenu01_item01.setMinimumSize(QtCore.QSize(40, 20))
        self.btnMenu01_item01.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnMenu01_item01.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnMenu01_item01.setStyleSheet("background-color: rgb(51, 140, 188);")
        self.btnMenu01_item01.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/btn/btn/btnWrite48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu01_item01.setIcon(icon)
        self.btnMenu01_item01.setObjectName("btnMenu01_item01")
        self.layMenu01.addWidget(self.btnMenu01_item01)
        self.btnMenu01_item02 = QtGui.QPushButton(self.wgMenu)
        self.btnMenu01_item02.setMinimumSize(QtCore.QSize(20, 20))
        self.btnMenu01_item02.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnMenu01_item02.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/btn/btn/btnArrowRight48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu01_item02.setIcon(icon1)
        self.btnMenu01_item02.setObjectName("btnMenu01_item02")
        self.layMenu01.addWidget(self.btnMenu01_item02)
        self.btnMenu01_item03 = QtGui.QPushButton(self.wgMenu)
        self.btnMenu01_item03.setMinimumSize(QtCore.QSize(20, 20))
        self.btnMenu01_item03.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnMenu01_item03.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/btn/btn/btnFile48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu01_item03.setIcon(icon2)
        self.btnMenu01_item03.setObjectName("btnMenu01_item03")
        self.layMenu01.addWidget(self.btnMenu01_item03)
        self.btnMenu01_line01 = QtGui.QFrame(self.wgMenu)
        self.btnMenu01_line01.setFrameShape(QtGui.QFrame.HLine)
        self.btnMenu01_line01.setFrameShadow(QtGui.QFrame.Sunken)
        self.btnMenu01_line01.setObjectName("btnMenu01_line01")
        self.layMenu01.addWidget(self.btnMenu01_line01)
        self.btnMenu01_item04 = QtGui.QPushButton(self.wgMenu)
        self.btnMenu01_item04.setMinimumSize(QtCore.QSize(20, 20))
        self.btnMenu01_item04.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnMenu01_item04.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/btn/btn/btnLog48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu01_item04.setIcon(icon3)
        self.btnMenu01_item04.setObjectName("btnMenu01_item04")
        self.layMenu01.addWidget(self.btnMenu01_item04)
        self.btnMenu01_item05 = QtGui.QPushButton(self.wgMenu)
        self.btnMenu01_item05.setMinimumSize(QtCore.QSize(20, 20))
        self.btnMenu01_item05.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnMenu01_item05.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/btn/btn/btnInboxE48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu01_item05.setIcon(icon4)
        self.btnMenu01_item05.setObjectName("btnMenu01_item05")
        self.layMenu01.addWidget(self.btnMenu01_item05)
        self.btnMenu01_item06 = QtGui.QPushButton(self.wgMenu)
        self.btnMenu01_item06.setMinimumSize(QtCore.QSize(20, 20))
        self.btnMenu01_item06.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnMenu01_item06.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/user/user/default.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu01_item06.setIcon(icon5)
        self.btnMenu01_item06.setObjectName("btnMenu01_item06")
        self.layMenu01.addWidget(self.btnMenu01_item06)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.layMenu01.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.layMenu01)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setContentsMargins(-1, 4, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtGui.QPushButton(self.wgMenu)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.layMenu02 = QtGui.QVBoxLayout()
        self.layMenu02.setSpacing(12)
        self.layMenu02.setContentsMargins(-1, 0, -1, -1)
        self.layMenu02.setObjectName("layMenu02")
        self.verticalLayout.addLayout(self.layMenu02)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.wgContent = QtGui.QWidget(self.wgMenu)
        self.wgContent.setObjectName("wgContent")
        self.layContent = QtGui.QVBoxLayout(self.wgContent)
        self.layContent.setContentsMargins(0, 0, 0, 0)
        self.layContent.setObjectName("layContent")
        self.horizontalLayout_8.addWidget(self.wgContent)
        self.horizontalLayout.addWidget(self.wgMenu)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenu01_item01.setToolTip(QtGui.QApplication.translate("Form", "data", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenu01_item02.setToolTip(QtGui.QApplication.translate("Form", "path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenu01_item03.setToolTip(QtGui.QApplication.translate("Form", "pipeline", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenu01_item04.setToolTip(QtGui.QApplication.translate("Form", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenu01_item05.setToolTip(QtGui.QApplication.translate("Form", "report", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMenu01_item06.setToolTip(QtGui.QApplication.translate("Form", "user", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
