# content   = Houdini config
# date      = 03.12.2024
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>

version: &HOUDINI_VERSION 19.5.773
path:    &HOUDINI_PATH !join ["C:/Program Files/Side Effects Software/Houdini ", *HOUDINI_VERSION, /bin/houdini.exe]

start: *HOUDINI_PATH

# renderer:
# renderer_path:


ENV:
    PYTHONPATH:
      - $software
      - $software/scripts
      - $software/plugins

    # HOUDINI_USER_PREF_DIR:
    #  - $config_project/houdini]
    # HOUDIN_PATH:
    #  - $config_project/houdini]

    HOUDINI_SPLASH_FILE: $img/software/houdini/houdini_splash.png

# MENU: plex/config/$project/houdini/MainMenuMaster.xml

# SETTINGS:
