# content   = 3ds Max config
# date      = 2020-06-19
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>

version: &MAX_VERSION 2023
path:    &MAX_PATH !join ["C:/Program Files/Autodesk/3ds Max ", *MAX_VERSION, /3dsmax.exe]

start: *MAX_PATH

# renderer:
# renderer_path:

ENV:
PYTHONPATH:
    - $software
    - $software/scripts
    - $software/apps
    - $software/icons

# ADSKFLEX_LICENSE_FILE:


#*********************************************************************
# MENU
#*********************************************************************
# MENU:
# - plex:
#     - open_scene_folder:   AddItem(MaxPlus.ActionFactory.Create('Open Scene Folder', 'Open Scene Folder', max_dcc.Max().open_scene_folder))
#     - open_project_folder: AddItem(MaxPlus.ActionFactory.Create('Open Project Folder', 'Open Project Folder', max_dcc.Max().open_project_folder))

# - break: AddSeparator()

# - Save:    AddItem(MaxPlus.ActionFactory.Create('Save', 'Save', max_dcc.Max().save))
# - Load:    AddItem(MaxPlus.ActionFactory.Create('Load', 'Load', max_dcc.Max().load))

# - break:   AddSeparator()

# - Report: "AddItem(MaxPlus.ActionFactory.Create('Report', 'Report', max_dcc.Max().report))"
# - Help:   "AddItem(MaxPlus.ActionFactory.Create('Help', 'Help', max_dcc.Max().help))"


# SETTINGS:
