# content   = Nuke config
# date      = 03.12.2024
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>

version:      &NUKE_VERSION 15.1                                
version_long: &NUKE_VERSION_LONG !join [*NUKE_VERSION, v1]      

start: !join ['start "" Nuke', *NUKE_VERSION ,'.exe --nukex {}']

path:  !join ["C:/Program Files/Nuke", *NUKE_VERSION_LONG,/Nuke, *NUKE_VERSION, .exe]


ENV:
    PYTHONPATH:
      - $software/scripts
      - $software/apps
      - $software/gizmos

    NUKE_PATH:
      - $plex
      - $software
      # - STATUS_PATH
      # - PLUGIN_PATH

    # Init & Menu
    NUKE_INIT_PATH: $software
    NUKE_MENU_PATH: $software

    NUKE_DIR: &NUKE_DIR !join ["C:/Program Files/Nuke", *NUKE_VERSION_LONG]

    PATH: *NUKE_DIR


#*********************************************************************
# MENU
#*********************************************************************
# MENU:
#   - Plex:
#       open_scene_folder:   addCommand('Open Scene Folder', 'import plexfunc; plexfunc.open_dir(nuke.root().knob("name").value())')
#       open_project_folder: addCommand('Open Project Folder', 'import plexfunc; plexfunc.open_dir(plex.config['project']["path"])')

#   - break:   addSeparator()

#   - Save:    "addCommand('Save', 'import menu; save()', 'ctrl+alt+s', 'save.ico')"
#   - Load:    "addCommand('Load', 'import menu; load()', 'ctrl+alt+l', 'load.ico')"

#   - break:   "addSeparator()"

#   - arWrite: addCommand('arWrite', 'arWrite()', 'ctrl+alt+w', 'write.ico')

#   - break:   addSeparator()

#   - Report:  addCommand('Report', 'import plexfunc; plexfunc.help("report")', 'ctrl+alt+r', 'report.ico')
#   - Help:    addCommand('Help', 'import plexfunc; plexfunc.help()', 'ctrl+alt+h', 'help.ico')

# SETTINGS:
