#*********************************************************************
# content   = software config
# date      = 2024-11-24
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>
#*********************************************************************

version: 10
path:    ''

# start command
start: ''

renderer:
renderer_path:

menu: menu_default


# Added BEFORE software starts
ENV:
    ENV_PATH: 