#*********************************************************************
# content   = pipeline config
# date      = 2024-11-09
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>
#*********************************************************************

name:    Plex
version: 2.1.0

url: https://github.com/alexanderrichtertd/plex


# ADMIN special rights (user name)
admin:
    - alexa
    - arichter


# RULES
shots:   s\d\d\d_  # s412_name
version: _v\d\d\d  # _v001
meta:    '/meta/info.yml'


STATUS:
    work:    WORK
    publish: PUBLISH
    render:  RENDER


# FORMATS
EXTENSION:
    maya:      ma
    max :      max
    nuke:      nk
    houdini:   hipnc
    photoshop: psd
    substance: spp

    playblast: mov
    texture:   exr
    render:    exr
    thumbnail: jpg

    icons:     png