# content   = plex config
# date      = 03.12.2024
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>

name: Plex
description: Open Source Pipeline
version: 2.5.0

url: https://github.com/alexanderrichtertd/plex
credit: Alexander Richter


# ANNOUNCEMENT shown in every application
# overwrite and show this announcement vs project
announcement_overwrite: False
announcement: Plex 2.5.0


# ADMIN special rights (user name)
admin:
    - alexa
    - arichter


# RULES
shots: s\d\d\d_  # s412_name
file_version: _v\d\d\d  # _v001


STATUS:
    work:    WORK
    publish: PUBLISH
    render:  RENDER


EXTENSION:
    maya:      ma
    max :      max
    nuke:      nk
    houdini:   hipnc
    photoshop: psd
    substance: spp

    playblast: mov
    texture:   exr
    render:    exr
    thumbnail: jpg

    icons:     png