# content   = plex config
# date      = 03.12.2024
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>

name: Plex
description: Open Source Pipeline
version: 2.5.0

url: https://github.com/alexanderrichtertd/plex
credit: Alexander Richter

# ANNOUNCEMENT shown in every application if set
announcement: Plex 2.5.0

plugin_extern: D:/plugins

# ADMIN special rights (user_id)
admin:
    - alexa
    - arichter
STATUS:
    work: WORK
    publish: PUBLISH
    render: RENDER

EXTENSION:
    maya: ma
    max: max
    nuke: nk
    houdini: hipnc
    photoshop: psd
    substance: spp

    playblast: mov
    texture: exr
    render: exr
    thumbnail: jpg

    icons: png
