!!python/unicode 'assetName_GEO_v002.ma':
    file_path: 
    img_path: 

    comment: Created an olive with paprika.
    user: arichter


!!python/unicode 's010_ANIM_v000.ma':
    comment: adding light and shader
    user: alexa

