# content   = scripts
# date      = 03.12.2024
#
# license   = MIT <https://github.com/alexanderrichtertd>
# author    = Alexander Richter <alexanderrichtertd.com>

# seperate with comma: save,report

# enable:   True|False
# software: os, maya, max, nuke, houdini, c4d, blender

#*********************************************************************
arUtil:
    progress_color:
        - lightblue
        - lightgreen
        - orange
        - red
    progress_img:
        - btn/btn_write
        - btn/btn_accept
        - btn/btn_warning
        - btn/btn_denial
#*********************************************************************
arNotice:
    enable: True
    timer: 7

#*********************************************************************
arSave:
    start:  &arSave import arSave; arSave.start()
    img:    &arSave_img png, jpg, tiff
    just_screenshot: True

#*********************************************************************
arLoad:
    img:    *arSave_img
    close_after: True

#*********************************************************************
arDesktop:
    auto_start: True
    style: "color: rgb(200, 200, 200);background-color: rgb(26, 30, 33);selection-background-color: rgb(60, 110, 190);"

    SOFTWARE:
        maya: self.press_btnOpenMaya
        max: self.press_btnOpenMax
        nuke: self.press_btnOpenNuke
        houdini: self.press_btnOpenHoudini

#*********************************************************************
arWrite:
    renderthreads: 12

achievement:
    enable: True

    # pipeline kid
    script_report:
        - 20
        - 100
        - 500
    # unbreakable
    script_crash:
        - 20
        - 100
        - 500
